

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD0
typedef void (*UniffiCallbackInterfaceElStackIssueEventDelegateMethod0)(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackIssueEventDelegateMethod0(
				UniffiCallbackInterfaceElStackIssueEventDelegateMethod0 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, key, value, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD1
typedef void (*UniffiCallbackInterfaceElStackIssueEventDelegateMethod1)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackIssueEventDelegateMethod1(
				UniffiCallbackInterfaceElStackIssueEventDelegateMethod1 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE_METHOD2
typedef void (*UniffiCallbackInterfaceElStackIssueEventDelegateMethod2)(uint64_t uniffi_handle, RustBuffer data, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackIssueEventDelegateMethod2(
				UniffiCallbackInterfaceElStackIssueEventDelegateMethod2 cb, uint64_t uniffi_handle, RustBuffer data, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, data, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD0
typedef void (*UniffiCallbackInterfaceElStackVpnEventDelegateMethod0)(uint64_t uniffi_handle, RustBuffer status, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackVpnEventDelegateMethod0(
				UniffiCallbackInterfaceElStackVpnEventDelegateMethod0 cb, uint64_t uniffi_handle, RustBuffer status, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, status, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD1
typedef void (*UniffiCallbackInterfaceElStackVpnEventDelegateMethod1)(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackVpnEventDelegateMethod1(
				UniffiCallbackInterfaceElStackVpnEventDelegateMethod1 cb, uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE_METHOD2
typedef void (*UniffiCallbackInterfaceElStackVpnEventDelegateMethod2)(uint64_t uniffi_handle, RustBuffer ip_addrs, RustBuffer dns_addrs, RustBuffer routes, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceElStackVpnEventDelegateMethod2(
				UniffiCallbackInterfaceElStackVpnEventDelegateMethod2 cb, uint64_t uniffi_handle, RustBuffer ip_addrs, RustBuffer dns_addrs, RustBuffer routes, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, ip_addrs, dns_addrs, routes, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EL_STACK_ISSUE_EVENT_DELEGATE
typedef struct UniffiVTableCallbackInterfaceElStackIssueEventDelegate {
    UniffiCallbackInterfaceElStackIssueEventDelegateMethod0 onGenerateAuthVp;
    UniffiCallbackInterfaceElStackIssueEventDelegateMethod1 onElPubKey;
    UniffiCallbackInterfaceElStackIssueEventDelegateMethod2 onElVpSign;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceElStackIssueEventDelegate;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EL_STACK_VPN_EVENT_DELEGATE
typedef struct UniffiVTableCallbackInterfaceElStackVpnEventDelegate {
    UniffiCallbackInterfaceElStackVpnEventDelegateMethod0 onStatusChange;
    UniffiCallbackInterfaceElStackVpnEventDelegateMethod1 onConnectionError;
    UniffiCallbackInterfaceElStackVpnEventDelegateMethod2 onLinkedParams;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceElStackVpnEventDelegate;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKISSUECONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKISSUECONFIG
void* uniffi_el_stack_fn_clone_elstackissueconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKISSUECONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKISSUECONFIG
void uniffi_el_stack_fn_free_elstackissueconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKISSUECONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKISSUECONFIG_NEW
void* uniffi_el_stack_fn_constructor_elstackissueconfig_new(RustBuffer el_issuer_url_prefix, RustBuffer el_issuer_pub_key, RustBuffer client_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKPRODUCTCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKPRODUCTCONFIG
void* uniffi_el_stack_fn_clone_elstackproductconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKPRODUCTCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKPRODUCTCONFIG
void uniffi_el_stack_fn_free_elstackproductconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKPRODUCTCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKPRODUCTCONFIG_NEW
void* uniffi_el_stack_fn_constructor_elstackproductconfig_new(RustBuffer product_name, RustBuffer product_version, RustBuffer os, RustBuffer ca_cert, uint64_t mtu, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKSOCKETBUFFERCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKSOCKETBUFFERCONFIG
void* uniffi_el_stack_fn_clone_elstacksocketbufferconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKSOCKETBUFFERCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKSOCKETBUFFERCONFIG
void uniffi_el_stack_fn_free_elstacksocketbufferconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKSOCKETBUFFERCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKSOCKETBUFFERCONFIG_NEW
void* uniffi_el_stack_fn_constructor_elstacksocketbufferconfig_new(uint64_t max_burst_size, RustBuffer tcp_buff_size, RustBuffer udp_buff_size, RustBuffer udp_meta_size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKVCCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKVCCONFIG
void* uniffi_el_stack_fn_clone_elstackvcconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKVCCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKVCCONFIG
void uniffi_el_stack_fn_free_elstackvcconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKVCCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKVCCONFIG_NEW
void* uniffi_el_stack_fn_constructor_elstackvcconfig_new(RustBuffer el_vc, RustBuffer el_vc_priv_key, RustBuffer el_issuer_pub_key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKVPNCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_ELSTACKVPNCONFIG
void* uniffi_el_stack_fn_clone_elstackvpnconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKVPNCONFIG
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_ELSTACKVPNCONFIG
void uniffi_el_stack_fn_free_elstackvpnconfig(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKVPNCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CONSTRUCTOR_ELSTACKVPNCONFIG_NEW
void* uniffi_el_stack_fn_constructor_elstackvpnconfig_new(RustBuffer server_host, RustBuffer server_serv, RustBuffer anti_overlap, uint64_t recv_timeout, uint64_t keepalive_interval, RustBuffer connection_type, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TCPLISTENER
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TCPLISTENER
void* uniffi_el_stack_fn_clone_tcplistener(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TCPLISTENER
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TCPLISTENER
void uniffi_el_stack_fn_free_tcplistener(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPLISTENER_ACCEPT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPLISTENER_ACCEPT
uint64_t uniffi_el_stack_fn_method_tcplistener_accept(void* ptr, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPLISTENER_BIND_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPLISTENER_BIND_ADDR
RustBuffer uniffi_el_stack_fn_method_tcplistener_bind_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TCPSTREAM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TCPSTREAM
void* uniffi_el_stack_fn_clone_tcpstream(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TCPSTREAM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TCPSTREAM
void uniffi_el_stack_fn_free_tcpstream(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_CLOSE
uint64_t uniffi_el_stack_fn_method_tcpstream_close(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_LOCAL_ADDR
RustBuffer uniffi_el_stack_fn_method_tcpstream_local_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_PEER_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_PEER_ADDR
RustBuffer uniffi_el_stack_fn_method_tcpstream_peer_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_RECV
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_RECV
uint64_t uniffi_el_stack_fn_method_tcpstream_recv(void* ptr, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_SEND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TCPSTREAM_SEND
uint64_t uniffi_el_stack_fn_method_tcpstream_send(void* ptr, RustBuffer buf, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TLSSTREAM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_TLSSTREAM
void* uniffi_el_stack_fn_clone_tlsstream(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TLSSTREAM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_TLSSTREAM
void uniffi_el_stack_fn_free_tlsstream(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_CLOSE
uint64_t uniffi_el_stack_fn_method_tlsstream_close(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_LOCAL_ADDR
RustBuffer uniffi_el_stack_fn_method_tlsstream_local_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_PEER_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_PEER_ADDR
RustBuffer uniffi_el_stack_fn_method_tlsstream_peer_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_RECV
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_RECV
uint64_t uniffi_el_stack_fn_method_tlsstream_recv(void* ptr, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_SEND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_TLSSTREAM_SEND
uint64_t uniffi_el_stack_fn_method_tlsstream_send(void* ptr, RustBuffer buf, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_UDPSOCKET
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_CLONE_UDPSOCKET
void* uniffi_el_stack_fn_clone_udpsocket(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_UDPSOCKET
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FREE_UDPSOCKET
void uniffi_el_stack_fn_free_udpsocket(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_LOCAL_ADDR
RustBuffer uniffi_el_stack_fn_method_udpsocket_local_addr(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_RECV_FROM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_RECV_FROM
uint64_t uniffi_el_stack_fn_method_udpsocket_recv_from(void* ptr, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_SEND_TO
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_METHOD_UDPSOCKET_SEND_TO
uint64_t uniffi_el_stack_fn_method_udpsocket_send_to(void* ptr, RustBuffer buf, RustBuffer target, uint64_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_INIT_CALLBACK_VTABLE_ELSTACKISSUEEVENTDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_INIT_CALLBACK_VTABLE_ELSTACKISSUEEVENTDELEGATE
void uniffi_el_stack_fn_init_callback_vtable_elstackissueeventdelegate(UniffiVTableCallbackInterfaceElStackIssueEventDelegate* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_INIT_CALLBACK_VTABLE_ELSTACKVPNEVENTDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_INIT_CALLBACK_VTABLE_ELSTACKVPNEVENTDELEGATE
void uniffi_el_stack_fn_init_callback_vtable_elstackvpneventdelegate(UniffiVTableCallbackInterfaceElStackVpnEventDelegate* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_INITIALIZE
void uniffi_el_stack_fn_func_initialize(void* product_config, void* socket_buffer_config, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_RESTART
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_RESTART
void uniffi_el_stack_fn_func_restart(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_START
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_START
uint64_t uniffi_el_stack_fn_func_start(uint64_t vpn_delegate, void* vpn_config, void* vc_config, RustBuffer capture_path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_STOP
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_STOP
void uniffi_el_stack_fn_func_stop(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TCP_BIND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TCP_BIND
uint64_t uniffi_el_stack_fn_func_tcp_bind(RustBuffer bind_addr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TCP_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TCP_CONNECT
uint64_t uniffi_el_stack_fn_func_tcp_connect(RustBuffer host, RustBuffer serv, uint64_t timeout_interval
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TLS_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_TLS_CONNECT
uint64_t uniffi_el_stack_fn_func_tls_connect(RustBuffer host, RustBuffer serv, uint64_t timeout_interval
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_UDP_BIND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_FN_FUNC_UDP_BIND
uint64_t uniffi_el_stack_fn_func_udp_bind(RustBuffer bind_addr
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_ALLOC
RustBuffer ffi_el_stack_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_el_stack_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_FREE
void ffi_el_stack_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUSTBUFFER_RESERVE
RustBuffer ffi_el_stack_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U8
void ffi_el_stack_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U8
void ffi_el_stack_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U8
void ffi_el_stack_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_el_stack_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I8
void ffi_el_stack_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I8
void ffi_el_stack_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I8
void ffi_el_stack_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I8
int8_t ffi_el_stack_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U16
void ffi_el_stack_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U16
void ffi_el_stack_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U16
void ffi_el_stack_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_el_stack_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I16
void ffi_el_stack_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I16
void ffi_el_stack_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I16
void ffi_el_stack_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I16
int16_t ffi_el_stack_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U32
void ffi_el_stack_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U32
void ffi_el_stack_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U32
void ffi_el_stack_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_el_stack_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I32
void ffi_el_stack_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I32
void ffi_el_stack_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I32
void ffi_el_stack_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I32
int32_t ffi_el_stack_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_U64
void ffi_el_stack_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_U64
void ffi_el_stack_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_U64
void ffi_el_stack_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_el_stack_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_I64
void ffi_el_stack_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_I64
void ffi_el_stack_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_I64
void ffi_el_stack_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_I64
int64_t ffi_el_stack_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_F32
void ffi_el_stack_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_F32
void ffi_el_stack_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_F32
void ffi_el_stack_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_F32
float ffi_el_stack_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_F64
void ffi_el_stack_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_F64
void ffi_el_stack_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_F64
void ffi_el_stack_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_F64
double ffi_el_stack_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_POINTER
void ffi_el_stack_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_POINTER
void ffi_el_stack_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_POINTER
void ffi_el_stack_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_POINTER
void* ffi_el_stack_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_el_stack_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_el_stack_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_el_stack_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_el_stack_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_POLL_VOID
void ffi_el_stack_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_CANCEL_VOID
void ffi_el_stack_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_FREE_VOID
void ffi_el_stack_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_EL_STACK_RUST_FUTURE_COMPLETE_VOID
void ffi_el_stack_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_INITIALIZE
uint16_t uniffi_el_stack_checksum_func_initialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_RESTART
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_RESTART
uint16_t uniffi_el_stack_checksum_func_restart(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_START
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_START
uint16_t uniffi_el_stack_checksum_func_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_STOP
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_STOP
uint16_t uniffi_el_stack_checksum_func_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TCP_BIND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TCP_BIND
uint16_t uniffi_el_stack_checksum_func_tcp_bind(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TCP_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TCP_CONNECT
uint16_t uniffi_el_stack_checksum_func_tcp_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TLS_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_TLS_CONNECT
uint16_t uniffi_el_stack_checksum_func_tls_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_UDP_BIND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_FUNC_UDP_BIND
uint16_t uniffi_el_stack_checksum_func_udp_bind(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPLISTENER_ACCEPT
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPLISTENER_ACCEPT
uint16_t uniffi_el_stack_checksum_method_tcplistener_accept(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPLISTENER_BIND_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPLISTENER_BIND_ADDR
uint16_t uniffi_el_stack_checksum_method_tcplistener_bind_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_CLOSE
uint16_t uniffi_el_stack_checksum_method_tcpstream_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_LOCAL_ADDR
uint16_t uniffi_el_stack_checksum_method_tcpstream_local_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_PEER_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_PEER_ADDR
uint16_t uniffi_el_stack_checksum_method_tcpstream_peer_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_RECV
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_RECV
uint16_t uniffi_el_stack_checksum_method_tcpstream_recv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_SEND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TCPSTREAM_SEND
uint16_t uniffi_el_stack_checksum_method_tcpstream_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_CLOSE
uint16_t uniffi_el_stack_checksum_method_tlsstream_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_LOCAL_ADDR
uint16_t uniffi_el_stack_checksum_method_tlsstream_local_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_PEER_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_PEER_ADDR
uint16_t uniffi_el_stack_checksum_method_tlsstream_peer_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_RECV
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_RECV
uint16_t uniffi_el_stack_checksum_method_tlsstream_recv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_SEND
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_TLSSTREAM_SEND
uint16_t uniffi_el_stack_checksum_method_tlsstream_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_LOCAL_ADDR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_LOCAL_ADDR
uint16_t uniffi_el_stack_checksum_method_udpsocket_local_addr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_RECV_FROM
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_RECV_FROM
uint16_t uniffi_el_stack_checksum_method_udpsocket_recv_from(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_SEND_TO
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_UDPSOCKET_SEND_TO
uint16_t uniffi_el_stack_checksum_method_udpsocket_send_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKISSUECONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKISSUECONFIG_NEW
uint16_t uniffi_el_stack_checksum_constructor_elstackissueconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKPRODUCTCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKPRODUCTCONFIG_NEW
uint16_t uniffi_el_stack_checksum_constructor_elstackproductconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKSOCKETBUFFERCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKSOCKETBUFFERCONFIG_NEW
uint16_t uniffi_el_stack_checksum_constructor_elstacksocketbufferconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKVCCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKVCCONFIG_NEW
uint16_t uniffi_el_stack_checksum_constructor_elstackvcconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKVPNCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_CONSTRUCTOR_ELSTACKVPNCONFIG_NEW
uint16_t uniffi_el_stack_checksum_constructor_elstackvpnconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_GENERATE_AUTH_VP
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_GENERATE_AUTH_VP
uint16_t uniffi_el_stack_checksum_method_elstackissueeventdelegate_on_generate_auth_vp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_EL_PUB_KEY
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_EL_PUB_KEY
uint16_t uniffi_el_stack_checksum_method_elstackissueeventdelegate_on_el_pub_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_EL_VP_SIGN
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKISSUEEVENTDELEGATE_ON_EL_VP_SIGN
uint16_t uniffi_el_stack_checksum_method_elstackissueeventdelegate_on_el_vp_sign(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_STATUS_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_STATUS_CHANGE
uint16_t uniffi_el_stack_checksum_method_elstackvpneventdelegate_on_status_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_CONNECTION_ERROR
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_CONNECTION_ERROR
uint16_t uniffi_el_stack_checksum_method_elstackvpneventdelegate_on_connection_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_LINKED_PARAMS
#define UNIFFI_FFIDEF_UNIFFI_EL_STACK_CHECKSUM_METHOD_ELSTACKVPNEVENTDELEGATE_ON_LINKED_PARAMS
uint16_t uniffi_el_stack_checksum_method_elstackvpneventdelegate_on_linked_params(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_EL_STACK_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_EL_STACK_UNIFFI_CONTRACT_VERSION
uint32_t ffi_el_stack_uniffi_contract_version(void
    
);
#endif

 void el_stack_cgo_dispatchCallbackInterfaceElStackIssueEventDelegateMethod0(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void el_stack_cgo_dispatchCallbackInterfaceElStackIssueEventDelegateMethod1(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void el_stack_cgo_dispatchCallbackInterfaceElStackIssueEventDelegateMethod2(uint64_t uniffi_handle, RustBuffer data, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void el_stack_cgo_dispatchCallbackInterfaceElStackIssueEventDelegateFree(uint64_t handle);
 void el_stack_cgo_dispatchCallbackInterfaceElStackVpnEventDelegateMethod0(uint64_t uniffi_handle, RustBuffer status, void* uniffi_out_return, RustCallStatus* callStatus );
 void el_stack_cgo_dispatchCallbackInterfaceElStackVpnEventDelegateMethod1(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );
 void el_stack_cgo_dispatchCallbackInterfaceElStackVpnEventDelegateMethod2(uint64_t uniffi_handle, RustBuffer ip_addrs, RustBuffer dns_addrs, RustBuffer routes, void* uniffi_out_return, RustCallStatus* callStatus );
 void el_stack_cgo_dispatchCallbackInterfaceElStackVpnEventDelegateFree(uint64_t handle);

void el_stack_uniffiFutureContinuationCallback(uint64_t, int8_t);
void el_stack_uniffiFreeGorutine(uint64_t);
